// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaOnline.Data;

#nullable disable

namespace SistemaOnline.Migrations
{
    [DbContext(typeof(APPDBContext))]
    partial class APPDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaOnline.Models.Carta", b =>
                {
                    b.Property<int>("ID_Carta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Carta"));

                    b.Property<int>("Cantidad_Platos")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre_Carta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("ID_Carta");

                    b.ToTable("Cartas");
                });

            modelBuilder.Entity("SistemaOnline.Models.Categoria_Ingrediente", b =>
                {
                    b.Property<int>("ID_Cat_Ingrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Cat_Ingrediente"));

                    b.Property<string>("Nombre_Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Cat_Ingrediente");

                    b.ToTable("Categorias_Ingredientes");
                });

            modelBuilder.Entity("SistemaOnline.Models.Cliente", b =>
                {
                    b.Property<int>("ID_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Cliente"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DNI")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RUC")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("ID_Cliente");

                    b.HasIndex("ID_Usuario")
                        .IsUnique()
                        .HasFilter("[ID_Usuario] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaOnline.Models.Comprobante_Pago", b =>
                {
                    b.Property<int>("ID_Comprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Comprobante"));

                    b.Property<string>("Direccion_Fiscal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado_Comprobante")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha_Emision")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int");

                    b.Property<decimal>("IGV")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Metodo_Pago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Monto_Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Numero_Comprobante")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RUC")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Razon_Social")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Serie")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Sub_Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo_Comprobante")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_Comprobante");

                    b.HasIndex("ID_Pedido");

                    b.ToTable("Comprobantes_Pagos");
                });

            modelBuilder.Entity("SistemaOnline.Models.Contrato_Empleado", b =>
                {
                    b.Property<int>("ID_Contrato_Empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Contrato_Empleado"));

                    b.Property<string>("Clausula")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Empleado")
                        .HasColumnType("int");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo_Contrato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Contrato_Empleado");

                    b.HasIndex("ID_Empleado");

                    b.ToTable("Contratos_Empleados");
                });

            modelBuilder.Entity("SistemaOnline.Models.Contrato_Proveedor", b =>
                {
                    b.Property<int>("ID_Contrato_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Contrato_Proveedor"));

                    b.Property<string>("Clausula")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Proveedor")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Contrato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Contrato_Proveedor");

                    b.HasIndex("ID_Proveedor");

                    b.ToTable("Contratos_Proveedores");
                });

            modelBuilder.Entity("SistemaOnline.Models.Empleado", b =>
                {
                    b.Property<int>("ID_Empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Empleado"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("ID_Empleado");

                    b.HasIndex("ID_Usuario")
                        .IsUnique()
                        .HasFilter("[ID_Usuario] IS NOT NULL");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SistemaOnline.Models.Empleado_Turno", b =>
                {
                    b.Property<int>("ID_Turno")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ID_Empleado")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ID_Turno", "ID_Empleado");

                    b.HasIndex("ID_Empleado");

                    b.ToTable("Empleados_Turnos");
                });

            modelBuilder.Entity("SistemaOnline.Models.Ingrediente", b =>
                {
                    b.Property<int>("ID_Ingrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Ingrediente"));

                    b.Property<decimal>("Costo_Unitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("ID_Cat_Ingrediente")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Ingrediente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unidad_Medida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_Ingrediente");

                    b.HasIndex("ID_Cat_Ingrediente");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("SistemaOnline.Models.Inventario", b =>
                {
                    b.Property<int>("ID_Inventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Inventario"));

                    b.Property<decimal>("Cantidad_Stock")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Fecha_Ultima_Reposicion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Ingrediente")
                        .HasColumnType("int");

                    b.Property<decimal>("Stock_Maximo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Stock_Minimo")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_Inventario");

                    b.HasIndex("ID_Ingrediente");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("SistemaOnline.Models.Mesa_Restaurante", b =>
                {
                    b.Property<int>("ID_Mesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Mesa"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Numero_Mesa")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Mesa");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("SistemaOnline.Models.Pago", b =>
                {
                    b.Property<int>("ID_Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Pago"));

                    b.Property<string>("Detalles_Tarjeta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Fecha_Hora_Pago")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int");

                    b.Property<string>("Metodo_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_Pago");

                    b.HasIndex("ID_Pedido");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("SistemaOnline.Models.Pedido", b =>
                {
                    b.Property<int>("ID_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Pedido"));

                    b.Property<string>("Estado_Pedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("ID_Empleado")
                        .HasColumnType("int");

                    b.Property<int>("ID_Mesa")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_Pedido");

                    b.HasIndex("ID_Cliente");

                    b.HasIndex("ID_Empleado");

                    b.HasIndex("ID_Mesa");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaOnline.Models.Pedido_Detalle", b =>
                {
                    b.Property<int>("ID_Pedido_Detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Pedido_Detalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("ID_Producto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_Pedido_Detalle");

                    b.HasIndex("ID_Pedido");

                    b.HasIndex("ID_Producto");

                    b.ToTable("Pedidos_Detalles");
                });

            modelBuilder.Entity("SistemaOnline.Models.Producto", b =>
                {
                    b.Property<int>("ID_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Producto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("bit");

                    b.Property<int>("ID_Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Plato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double>("Tiempo_Preparacion")
                        .HasColumnType("float");

                    b.HasKey("ID_Producto");

                    b.HasIndex("ID_Categoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SistemaOnline.Models.Producto_Categoria", b =>
                {
                    b.Property<int>("ID_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Categoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ID_Carta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Categoria");

                    b.HasIndex("ID_Carta");

                    b.ToTable("Productos_Categorias");
                });

            modelBuilder.Entity("SistemaOnline.Models.Producto_Ingrediente", b =>
                {
                    b.Property<int>("ID_Producto_Ingrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Producto_Ingrediente"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("ID_Ingrediente")
                        .HasColumnType("int");

                    b.Property<int>("ID_Producto")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unidad_Medida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Producto_Ingrediente");

                    b.HasIndex("ID_Ingrediente");

                    b.HasIndex("ID_Producto");

                    b.ToTable("Productos_Ingredientes");
                });

            modelBuilder.Entity("SistemaOnline.Models.Producto_Promocion", b =>
                {
                    b.Property<int>("ID_Producto")
                        .HasColumnType("int");

                    b.Property<int>("ID_Promocion")
                        .HasColumnType("int");

                    b.HasKey("ID_Producto", "ID_Promocion");

                    b.HasIndex("ID_Promocion");

                    b.ToTable("Productos_Promociones");
                });

            modelBuilder.Entity("SistemaOnline.Models.Promocion", b =>
                {
                    b.Property<int>("ID_Promocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Promocion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Porcentaje_Descuento")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ID_Promocion");

                    b.ToTable("Promociones");
                });

            modelBuilder.Entity("SistemaOnline.Models.Proveedor", b =>
                {
                    b.Property<int>("ID_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Proveedor"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email_Contacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre_Empresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Tipo_Suministro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID_Proveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SistemaOnline.Models.Proveedor_Ingrediente", b =>
                {
                    b.Property<int>("ID_Proveedor")
                        .HasColumnType("int");

                    b.Property<int>("ID_Ingrediente")
                        .HasColumnType("int");

                    b.HasKey("ID_Proveedor", "ID_Ingrediente");

                    b.HasIndex("ID_Ingrediente");

                    b.ToTable("Proveedores_Ingredientes");
                });

            modelBuilder.Entity("SistemaOnline.Models.Reservacion", b =>
                {
                    b.Property<int>("ID_Reservacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Reservacion"));

                    b.Property<string>("Estado_Reservacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Fecha_Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("ID_Mesa")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Numero_Personas")
                        .HasColumnType("int");

                    b.Property<string>("Ocasion_Especial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Reservacion");

                    b.HasIndex("ID_Cliente");

                    b.HasIndex("ID_Mesa");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("SistemaOnline.Models.Rol", b =>
                {
                    b.Property<int>("ID_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Rol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre_Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaOnline.Models.Turno", b =>
                {
                    b.Property<int>("ID_Turno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Turno"));

                    b.Property<string>("Dias_Semana")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<TimeSpan>("Hora_Fin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Hora_Inicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre_Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Turno");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("SistemaOnline.Models.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("ID_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID_Usuario");

                    b.HasIndex("ID_Rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaOnline.Models.Cliente", b =>
                {
                    b.HasOne("SistemaOnline.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("SistemaOnline.Models.Cliente", "ID_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaOnline.Models.Comprobante_Pago", b =>
                {
                    b.HasOne("SistemaOnline.Models.Pedido", "Pedido")
                        .WithMany("Comprobantes_Pago")
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SistemaOnline.Models.Contrato_Empleado", b =>
                {
                    b.HasOne("SistemaOnline.Models.Empleado", "Empleado")
                        .WithMany("Contratos")
                        .HasForeignKey("ID_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SistemaOnline.Models.Contrato_Proveedor", b =>
                {
                    b.HasOne("SistemaOnline.Models.Proveedor", "Proveedor")
                        .WithMany("Contratos")
                        .HasForeignKey("ID_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SistemaOnline.Models.Empleado", b =>
                {
                    b.HasOne("SistemaOnline.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("SistemaOnline.Models.Empleado", "ID_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaOnline.Models.Empleado_Turno", b =>
                {
                    b.HasOne("SistemaOnline.Models.Empleado", "Empleado")
                        .WithMany("Empleado_Turnos")
                        .HasForeignKey("ID_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOnline.Models.Turno", "Turno")
                        .WithMany("Empleado_Turnos")
                        .HasForeignKey("ID_Turno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaOnline.Models.Ingrediente", b =>
                {
                    b.HasOne("SistemaOnline.Models.Categoria_Ingrediente", "Categoria_Ingrediente")
                        .WithMany("Ingredientes")
                        .HasForeignKey("ID_Cat_Ingrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria_Ingrediente");
                });

            modelBuilder.Entity("SistemaOnline.Models.Inventario", b =>
                {
                    b.HasOne("SistemaOnline.Models.Ingrediente", "Ingrediente")
                        .WithMany("Inventarios")
                        .HasForeignKey("ID_Ingrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("SistemaOnline.Models.Pago", b =>
                {
                    b.HasOne("SistemaOnline.Models.Pedido", "Pedido")
                        .WithMany("Pagos")
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SistemaOnline.Models.Pedido", b =>
                {
                    b.HasOne("SistemaOnline.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ID_Cliente");

                    b.HasOne("SistemaOnline.Models.Empleado", "Empleado")
                        .WithMany("Pedidos")
                        .HasForeignKey("ID_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOnline.Models.Mesa_Restaurante", "Mesa_Restaurante")
                        .WithMany("Pedidos")
                        .HasForeignKey("ID_Mesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Mesa_Restaurante");
                });

            modelBuilder.Entity("SistemaOnline.Models.Pedido_Detalle", b =>
                {
                    b.HasOne("SistemaOnline.Models.Pedido", "Pedido")
                        .WithMany("Pedido_Detalles")
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOnline.Models.Producto", "Producto")
                        .WithMany("Pedido_Detalles")
                        .HasForeignKey("ID_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaOnline.Models.Producto", b =>
                {
                    b.HasOne("SistemaOnline.Models.Producto_Categoria", "Producto_Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("ID_Categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto_Categoria");
                });

            modelBuilder.Entity("SistemaOnline.Models.Producto_Categoria", b =>
                {
                    b.HasOne("SistemaOnline.Models.Carta", "Carta")
                        .WithMany("Producto_Categorias")
                        .HasForeignKey("ID_Carta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");
                });

            modelBuilder.Entity("SistemaOnline.Models.Producto_Ingrediente", b =>
                {
                    b.HasOne("SistemaOnline.Models.Ingrediente", "Ingrediente")
                        .WithMany("Producto_Ingredientes")
                        .HasForeignKey("ID_Ingrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOnline.Models.Producto", "Producto")
                        .WithMany("Producto_Ingredientes")
                        .HasForeignKey("ID_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SistemaOnline.Models.Producto_Promocion", b =>
                {
                    b.HasOne("SistemaOnline.Models.Producto", "Producto")
                        .WithMany("Producto_Promociones")
                        .HasForeignKey("ID_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOnline.Models.Promocion", "Promocion")
                        .WithMany("Producto_Promociones")
                        .HasForeignKey("ID_Promocion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Promocion");
                });

            modelBuilder.Entity("SistemaOnline.Models.Proveedor_Ingrediente", b =>
                {
                    b.HasOne("SistemaOnline.Models.Ingrediente", "Ingrediente")
                        .WithMany("Proveedor_Ingredientes")
                        .HasForeignKey("ID_Ingrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOnline.Models.Proveedor", "Proveedor")
                        .WithMany("Proveedor_Ingredientes")
                        .HasForeignKey("ID_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SistemaOnline.Models.Reservacion", b =>
                {
                    b.HasOne("SistemaOnline.Models.Cliente", "Cliente")
                        .WithMany("Reservaciones")
                        .HasForeignKey("ID_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOnline.Models.Mesa_Restaurante", "Mesa_Restaurante")
                        .WithMany("Reservaciones")
                        .HasForeignKey("ID_Mesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Mesa_Restaurante");
                });

            modelBuilder.Entity("SistemaOnline.Models.Usuario", b =>
                {
                    b.HasOne("SistemaOnline.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("ID_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaOnline.Models.Carta", b =>
                {
                    b.Navigation("Producto_Categorias");
                });

            modelBuilder.Entity("SistemaOnline.Models.Categoria_Ingrediente", b =>
                {
                    b.Navigation("Ingredientes");
                });

            modelBuilder.Entity("SistemaOnline.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Reservaciones");
                });

            modelBuilder.Entity("SistemaOnline.Models.Empleado", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Empleado_Turnos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SistemaOnline.Models.Ingrediente", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("Producto_Ingredientes");

                    b.Navigation("Proveedor_Ingredientes");
                });

            modelBuilder.Entity("SistemaOnline.Models.Mesa_Restaurante", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Reservaciones");
                });

            modelBuilder.Entity("SistemaOnline.Models.Pedido", b =>
                {
                    b.Navigation("Comprobantes_Pago");

                    b.Navigation("Pagos");

                    b.Navigation("Pedido_Detalles");
                });

            modelBuilder.Entity("SistemaOnline.Models.Producto", b =>
                {
                    b.Navigation("Pedido_Detalles");

                    b.Navigation("Producto_Ingredientes");

                    b.Navigation("Producto_Promociones");
                });

            modelBuilder.Entity("SistemaOnline.Models.Producto_Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SistemaOnline.Models.Promocion", b =>
                {
                    b.Navigation("Producto_Promociones");
                });

            modelBuilder.Entity("SistemaOnline.Models.Proveedor", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Proveedor_Ingredientes");
                });

            modelBuilder.Entity("SistemaOnline.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaOnline.Models.Turno", b =>
                {
                    b.Navigation("Empleado_Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
